### PR TITLE
venkat version of madlibs story

### PR DESCRIPTION
**Pull request by chintalapativenkat**
Please Check my Version

### CODE REVIEW

**Review by jspark410 — APPROVED** [review]
I want to swim there!

**Comment by chintalapativenkat** [comment]
Changes Performed to Resolve Conflicts

**Comment by jspark410** [comment]
Great! It looks perfect!

**Review by jspark410 — COMMENTED** [review]
It looks perfect!

**Review by jspark410 — COMMENTED** [review]
I like this story

**Pull request merged**
